set Color(Start) black
set Color(Goal) black
set Color(StartArrow) white
set Color(GoalArrow) white
set Color(Path) black
set Color(PushEdge)  black
set Color(Animate) white
set Color(Obstacle) black
set Color(CurrentObstacle) black
set Color(SelectedObstacle) black
set Color(ObEdit,GridMark) black
set Color(Object) black
set Color(pushable) white
set Color(help) black
set Color(edgeline) black
set Color(fricline) black
set Color(PlannerButtonbg) black
set Color(PlannerButtonfg) white