set Color(Start) red
set Color(Goal) #1f1
set Color(StartArrow) white
set Color(GoalArrow) #222
set Color(Path) #0b0
set Color(PushEdge)  #00c
set Color(Animate) #0bf
set Color(Obstacle) blue
set Color(CurrentObstacle) #47f
set Color(SelectedObstacle) yellow
set Color(ObEdit,GridMark) #040
set Color(Object) orange
set Color(pushable) #f000fffff000
set Color(help) #c0c
set Color(edgeline) yellow
set Color(fricline) purple
set Color(PlannerButtonbg) red
set Color(PlannerButtonfg) white